# Generated by Django 4.1 on 2023-07-31 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_publicada',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
